### ISSUE TITLE
error: CRAWLER Error Error: options.uri is a required argument when fetching undefined (3 retries left)

### ISSUE THREAD

**Issue by JeetChan** [f111fei/article_spider#9]
在爬取公众号 **openmindworld** 时发生错误：

`正在解析文章数据:{"id":"1000000353","title":""}
2020-03-24T12:58:53.713Z - error: CRAWLER Error Error: options.uri is a required argument when fetching undefined (3 retries left)
2020-03-24T12:59:03.721Z - error: CRAWLER Error Error: options.uri is a required argument when fetching undefined (2 retries left)
2020-03-24T12:59:13.737Z - error: CRAWLER Error Error: options.uri is a required argument when fetching undefined (1 retries left)
2020-03-24T12:59:23.745Z - error: CRAWLER Error Error: options.uri is a required argument when fetching undefined
(node:3147) UnhandledPromiseRejectionWarning: Error: Error: options.uri is a required argument
    at Step.<anonymous> (/home/jeetchan/article_spider/node_modules/step-pipe/out/index.js:31:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/jeetchan/article_spider/node_modules/step-pipe/out/index.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by 1015zhc** [comment]
你好，127.0.0.1:9222/json这一步能打开吗，我的打不开

**Comment by JeetChan** [comment]
> 你好，127.0.0.1:9222/json这一步能打开吗，我的打不开

可以。不过现在公众号越来越难抓取了。
